# version: "3.7"

services:
  laravel:
    image: yaraku/assignment:$COMPOSE_PROJECT_NAME
    container_name: $COMPOSE_PROJECT_NAME-laravel
    environment:
      # DB_DATABASE: laravel-react-books
      # DB_HOST: $COMPOSE_PROJECT_NAME-mysql
      # DB_PASSWORD: secret
      # DB_USERNAME: laravel
      # DB_PASSWORD: root
      # DB_USERNAME: root
      APP_DEBUG: 'true'
      APP_ENV: local
      APP_KEY: base64:VLDiZb0zk+Z0Uta4UeapjplAt3oG4PIodlTKvJX4ZkQ=
      LOG_CHANNEL: stderr
    ports:
    - '80:80'
    volumes:
    - ./src:/var/www/html
    # depends_on:
    #   - $COMPOSE_PROJECT_NAME-mysql
    restart: always

  mysql:
    image: mysql:8.3
    container_name: $COMPOSE_PROJECT_NAME-mysql
    ports:
      - '3399:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
